---
name: "prepare-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Prepare Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"
